apiVersion: batch/v1
kind: Job
metadata:
  name: quran-hadith-ingestion-job
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: ingest
        image: 610714125174.dkr.ecr.ap-south-1.amazonaws.com/quran-hadith-rag-api:latest
        command: ["python", "ingest.py"]
        env:
        - name: QDRANT_HOST
          value: "qdrant-svc"
        - name: QDRANT_PORT
          value: "6333"
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
